- name: Install Shade on Red Hat Openstack Director
  hosts: undercloud
  vars:
    - packages:
        - python-virtualenv
  tasks:
    - name: Install package(s) for Python VirtualEnv
      yum:
        state: latest
        name: "{{ item }}"
      with_items: "{{ packages }}"
      become: True
      become_method: sudo
      become_user: root
    - name: Pip install setuptools and shade in Virtualenv called shade
      pip:
        virtualenv: /home/stack/shade
        virtualenv_command: virtualenv
        virtualenv_site_packages: yes
        extra_args: --upgrade
        name: "{{ item }}"
      with_items:
        - setuptools
        - shade
    - name: Obtain name of overcloud to determine rc file
      shell: |
        source ~/stackrc
        openstack stack list -c "Stack Name" -f value
      register: stack_list
    - name: Create clouds.yaml.config file with undercloud data
      shell: |
        mkdir -p ~/.config/openstack 2>/dev/null
        if [[ -f ~/.config/openstack/clouds.yaml ]]
        then
          mv ~/.config/openstack/clouds.yaml ~/.config/openstack/clouds.yaml.$(date +'%Y%m%d-%H%M')
        fi
        echo 'clouds:' >~/.config/openstack/clouds.yaml.config
        RC_FILE=~/stackrc
        if [[ -f ${RC_FILE} ]]
        then
          source ${RC_FILE}
          OS_REGIONNAME=$(openstack endpoint list -c Region -f value | sort -u | head -1)

          if [[ -z "${OS_TENANT_NAME}" ]]
          then
            OS_TENANT_NAME=${OS_PROJECT_NAME}
          fi

          echo "  ${OS_CLOUDNAME}:" >>~/.config/openstack/clouds.yaml.config
          echo "    region_name: ${OS_REGIONNAME}" >>~/.config/openstack/clouds.yaml.config
          echo "    auth:" >>~/.config/openstack/clouds.yaml.config
          echo "      username: '${OS_USERNAME}'" >>~/.config/openstack/clouds.yaml.config
          echo "      password: ${OS_PASSWORD}" >>~/.config/openstack/clouds.yaml.config
          echo "      project_name: '${OS_TENANT_NAME}'" >>~/.config/openstack/clouds.yaml.config
          echo "      auth_url: '${OS_AUTH_URL}'" >>~/.config/openstack/clouds.yaml.config
        fi
    - name: Add overcloud to clouds.yaml.config
      shell: |
        RC_FILE=~/{{ stack_list.stdout }}rc
        if [[ -f ${RC_FILE} ]]
        then
          source ${RC_FILE}
          OS_REGIONNAME=$(openstack endpoint list -c Region -f value | sort -u | head -1)

          if [[ -z "${OS_TENANT_NAME}" ]]
          then
            OS_TENANT_NAME=${OS_PROJECT_NAME}
          fi

          echo "  ${OS_CLOUDNAME}:" >>~/.config/openstack/clouds.yaml.config
          echo "    region_name: ${OS_REGIONNAME}" >>~/.config/openstack/clouds.yaml.config
          echo "    auth:" >>~/.config/openstack/clouds.yaml.config
          echo "      username: '${OS_USERNAME}'" >>~/.config/openstack/clouds.yaml.config
          echo "      password: ${OS_PASSWORD}" >>~/.config/openstack/clouds.yaml.config
          echo "      project_name: '${OS_TENANT_NAME}'" >>~/.config/openstack/clouds.yaml.config
          echo "      auth_url: '${OS_AUTH_URL}'" >>~/.config/openstack/clouds.yaml.config
        fi
      when: stack_list.stdout != ""
    - name: Move clouds.yaml into place
      copy:
        src: ~/.config/openstack/clouds.yaml.config
        dest: ~/.config/openstack/clouds.yaml
        remote_src: True
    - name: Clean up clouds.yaml.config
      file:
        path: ~/.config/openstack/clouds.yaml.config
        state: absent
